#!/usr/bin/env python3
"""Generate the English ver4 subpages from one narrative and visual system.

The homepage stays hand-crafted. This generator owns every English HTML page
except index.html and keeps the prototype coherent while the information
architecture is still evolving.
"""
from html import escape
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VERSION = "20260813"


def visual(kind):
    if kind == "model":
        return '''<div class="v4p-canvas v4p-diagram-model"><span class="v4p-canvas-label">ONE LIVING APPLICATION MODEL</span>
        <div class="v4p-window"><div class="v4p-window-head"><span>SPECIFICATION</span><i></i></div><div class="v4p-mini-lines"><span></span><span></span><span></span></div></div>
        <div class="v4p-window"><div class="v4p-window-head"><span>WORKING APPLICATION</span><i></i></div><div class="v4p-mini-lines"><span></span><span></span><span></span></div></div>
        <div class="v4p-flow-line"></div><div class="v4p-model-core"><div>2to2<small>LIVING MODEL</small></div></div>
        <div class="v4p-chip-row"><span class="v4p-chip"><i></i>PROCESS</span><span class="v4p-chip"><i></i>DATA</span><span class="v4p-chip"><i></i>PAGES</span></div>
        <p class="v4p-visual-caption">Change either view. The model keeps both aligned.</p></div>'''
    if kind == "compiler":
        return '''<div class="v4p-canvas v4p-diagram-compiler"><span class="v4p-canvas-label">APP AI CREATOR</span>
        <div class="v4p-spec-sheet"><span class="v4p-kicker">STRUCTURED SPECIFICATION</span><h4>Vendor onboarding</h4><p>Roles: Buyer, Compliance</p><p>Data: vendor, risk score</p><p class="rule">High-risk vendors require approval.</p></div>
        <div class="v4p-model-core"><div>AI<small>COMPILER</small></div></div>
        <div class="v4p-object-stack"><div class="v4p-object"><i></i><div><strong>Process</strong><small>7 states · 12 actions</small></div><b>✓</b></div><div class="v4p-object"><i style="background:#60a5fa"></i><div><strong>Data model</strong><small>5 lists · 41 fields</small></div><b>✓</b></div><div class="v4p-object"><i style="background:#fbbf24"></i><div><strong>Pages</strong><small>8 pages · 3 views</small></div><b>✓</b></div><div class="v4p-object"><i style="background:#c084fc"></i><div><strong>Permissions</strong><small>4 groups · 18 rules</small></div><b>✓</b></div></div>
        <p class="v4p-visual-caption">The result is native 2to2 objects — not generated source code.</p></div>'''
    if kind == "apps":
        return '''<div class="v4p-canvas v4p-diagram-apps"><span class="v4p-canvas-label">NO-CODE APPLICATION DESIGNER</span><div class="v4p-app-shell"><div class="v4p-app-nav"><span class="active">Application</span><span>Data model</span><span>Process</span><span>Pages</span><span>Access</span></div><div class="v4p-app-main"><span class="v4p-kicker">VENDOR ONBOARDING</span><h4>New vendor request</h4><div class="v4p-form-grid"><div class="v4p-field"><span>COMPANY NAME</span><i></i></div><div class="v4p-field"><span>RISK CATEGORY</span><i></i></div><div class="v4p-field"><span>REQUESTER</span><i></i></div><div class="v4p-field"><span>OWNER</span><i></i></div><div class="v4p-form-process"><b>Draft</b><span>→</span><b class="active">Review</b><span>→</span><b>Approval</b></div></div></div></div></div>'''
    if kind == "process":
        return '''<div class="v4p-canvas v4p-diagram-process"><span class="v4p-canvas-label">STATE-BASED PROCESS ENGINE</span><svg viewBox="0 0 560 500" aria-hidden="true"><defs><marker id="v4pArrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto"><path d="M0 0 10 5 0 10z" fill="#64748b"/></marker></defs><path d="M154 136h70M336 136h70M464 168v130M406 329h-68M220 329h-68M96 298V168" fill="none" stroke="#475569" stroke-width="2" stroke-dasharray="6 6" marker-end="url(#v4pArrow)"/></svg><div class="v4p-state s1">Draft</div><div class="v4p-state s2">AI check</div><div class="v4p-state s3">Review</div><div class="v4p-state s4">Approval</div><div class="v4p-state s5">Active</div><p class="v4p-visual-caption">State defines what can happen next, who may act and which rules apply.</p></div>'''
    if kind == "workers":
        return '''<div class="v4p-canvas v4p-diagram-workers"><span class="v4p-canvas-label">ONE PROCESS · DIFFERENT EXECUTORS</span><div class="v4p-person"><div class="v4p-avatar">H</div><strong>HUMAN</strong></div><div class="v4p-flow-line"></div><div class="v4p-model-core"><div>2to2<small>PROCESS</small></div></div><div class="v4p-worker"><div class="v4p-avatar" style="color:#5eead4;border-color:#2dd4bf">AI</div><strong>DIGITAL WORKER</strong></div><p class="v4p-visual-caption">Same process, permissions, accountability and audit trail.</p></div>'''
    if kind == "governance":
        return '''<div class="v4p-canvas v4p-diagram-governance"><span class="v4p-canvas-label">GOVERNANCE IS THE RUNTIME</span><div class="v4p-shield"></div><div class="v4p-shield-inner">✓</div><div class="v4p-governance-ring"></div><div class="v4p-governance-points"><span>IDENTITY</span><span>ROLE</span><span>STATE</span><span>APPROVAL</span><span>AUDIT</span></div><p class="v4p-visual-caption">Control is applied while work happens — not reconstructed afterwards.</p></div>'''
    if kind == "pilot":
        return '''<div class="v4p-canvas v4p-diagram-pilot"><span class="v4p-canvas-label">FROM ONE PROCESS TO A PLATFORM</span><div class="v4p-timeline"></div><div class="v4p-milestone m1"><strong>PILOT</strong><small>one real process</small></div><div class="v4p-milestone m2"><strong>PRODUCTION</strong><small>real roles and data</small></div><div class="v4p-milestone m3"><strong>SCALE</strong><small>more apps and teams</small></div><p class="v4p-visual-caption">The pilot uses the same model and runtime as production.</p></div>'''
    raise ValueError(kind)


def hero(eyebrow, title, lead, kind, primary=("Talk about a pilot", "contact.html"), secondary=("See how it works", "how-it-works.html"), proof=()):
    lis = ''.join(f'<li>{x}</li>' for x in proof)
    return f'''<section class="v4p-hero"><div class="v4p-shell v4p-hero-grid"><div class="v4p-hero-copy"><p class="v4p-eyebrow">{eyebrow}</p><h1>{title}</h1><p class="v4p-hero-lead">{lead}</p><div class="v4p-actions"><a class="v4p-button v4p-button-primary" href="{primary[1]}">{primary[0]} <span>→</span></a><a class="v4p-button v4p-button-secondary" href="{secondary[1]}">{secondary[0]}</a></div><ul class="v4p-proof">{lis}</ul></div><div class="v4p-hero-visual">{visual(kind)}</div></div></section>'''


def strip(text, facts):
    return f'''<section class="v4p-strip"><div class="v4p-shell v4p-strip-inner"><p>{text}</p><div class="v4p-strip-facts">{''.join(f'<span>{x}</span>' for x in facts)}</div></div></section>'''


def head(kicker, title, intro="", center=False):
    return f'''<div class="v4p-section-head{' center' if center else ''}"><p class="v4p-kicker">{kicker}</p><h2>{title}</h2>{f'<p>{intro}</p>' if intro else ''}</div>'''


def cards(kicker, title, intro, items, cols=3, soft=False, center=False, section_id=""):
    rendered = []
    for i, item in enumerate(items, 1):
        if len(item) == 3: name, copy, link = item
        else: name, copy = item; link = None
        link_html = f'<a href="{link[1]}">{link[0]} <span>→</span></a>' if link else ''
        rendered.append(f'<article class="v4p-card"><span class="v4p-card-number">{i:02}</span><h3>{name}</h3><p>{copy}</p>{link_html}</article>')
    return f'''<section class="v4p-section{' v4p-section-soft' if soft else ''}"{f' id="{section_id}"' if section_id else ''}><div class="v4p-shell">{head(kicker,title,intro,center)}<div class="v4p-grid v4p-grid-{cols}">{''.join(rendered)}</div></div></section>'''


def split(kicker, title, intro, bullets, panel_title, panel_intro, objects, reverse=False, soft=False):
    obj = ''.join(f'<div class="v4p-object"><i style="background:{color}"></i><div><strong>{name}</strong><small>{copy}</small></div><b>{mark}</b></div>' for name,copy,color,mark in objects)
    return f'''<section class="v4p-section{' v4p-section-soft' if soft else ''}"><div class="v4p-shell"><div class="v4p-split{' reverse' if reverse else ''}"><div class="v4p-split-copy"><p class="v4p-kicker">{kicker}</p><h2>{title}</h2><p>{intro}</p><ul>{''.join(f'<li>{x}</li>' for x in bullets)}</ul></div><aside class="v4p-side-panel"><h3>{panel_title}</h3><p>{panel_intro}</p>{obj}</aside></div></div></section>'''


def steps(kicker, title, intro, items):
    return f'''<section class="v4p-section v4p-section-soft"><div class="v4p-shell">{head(kicker,title,intro,True)}<div class="v4p-steps">{''.join(f'<article class="v4p-step"><span>{i:02}</span><h3>{n}</h3><p>{c}</p></article>' for i,(n,c) in enumerate(items,1))}</div></div></section>'''


def compare(kicker, title, intro, left, right, rows):
    body = ''.join(f'<div class="v4p-compare-row"><div data-label="Question">{q}</div><div data-label="{left}" class="{lc}">{l}</div><div data-label="{right}" class="{rc}">{r}</div></div>' for q,l,r,lc,rc in rows)
    return f'''<section class="v4p-section"><div class="v4p-shell">{head(kicker,title,intro)}<div class="v4p-compare"><div class="v4p-compare-row v4p-compare-head"><div></div><div>{left}</div><div>{right}</div></div>{body}</div></div></section>'''


def quote(text, note):
    return f'''<section class="v4p-section v4p-section-teal"><div class="v4p-shell"><div class="v4p-quote"><blockquote>{text}</blockquote><p>{note}</p></div></div></section>'''


def stats(items):
    return f'''<section class="v4p-section v4p-section-soft"><div class="v4p-shell"><div class="v4p-stats">{''.join(f'<div class="v4p-stat"><strong>{n}</strong><span>{c}</span></div>' for n,c in items)}</div></div></section>'''


def logos():
    return '''<div class="v4p-logos" aria-label="Organizations using Datapolis workflow products"><img src="storage/files/klienci/logo-airbus.png" alt="Airbus"><img src="storage/files/klienci/logo-pgnig.png" alt="PGNiG"><img src="storage/files/klienci/logo-thyssenkrupp.png" alt="thyssenkrupp"><img src="storage/files/klienci/logo-polskie-radio.png" alt="Polskie Radio"><img src="storage/files/klienci/logo-nexia.png" alt="Nexia"></div>'''


def final(title="Bring one real business process. Let’s turn it into a living application.", copy="Start with a focused pilot: real roles, real rules and a working 2to2 application generated from its specification."):
    return f'''<section class="v4p-final"><div class="v4p-shell v4p-final-inner"><p class="v4p-kicker">SEE THE IDEA WORKING</p><h2>{title}</h2><p>{copy}</p><div class="v4p-actions"><a class="v4p-button v4p-button-primary" href="contact.html">Talk about a pilot <span>→</span></a><a class="v4p-button v4p-button-secondary" href="platform-2to2.html">Explore 2to2</a></div></div></section>'''


def page(title, desc, slug, body, alternates=True, extra_head=""):
    canonical = "https://datapolis.com/" + slug
    alt = ''
    if alternates:
        alt = ''.join(f'<link rel="alternate" hreflang="{lang}" href="https://datapolis.com/{prefix}{slug}">' for lang,prefix in (("en",""),("pl","pl/"),("de","de/"),("es","es/")))
    alt += f'<link rel="alternate" hreflang="x-default" href="{canonical}">'
    return f'''<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><title>{escape(title)}</title><meta name="description" content="{escape(desc, quote=True)}"><meta name="robots" content="index,follow"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#020617"><link rel="canonical" href="{canonical}">{alt}<meta property="og:title" content="{escape(title, quote=True)}"><meta property="og:description" content="{escape(desc, quote=True)}"><meta property="og:type" content="website"><meta property="og:url" content="{canonical}"><meta property="og:locale" content="en_US"><meta property="og:image" content="https://datapolis.com/assets/img/og-image-1200x630.png"><meta name="twitter:card" content="summary_large_image"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&amp;family=Instrument+Sans:wght@400;500;600;700&amp;display=swap"><link rel="stylesheet" href="assets/css/main.min.css?v={VERSION}"><link rel="stylesheet" href="assets/css/async.min.css?v={VERSION}" media="print" onload="this.media='all';this.onload=null"><link rel="stylesheet" href="assets/css/dark-theme.css?v={VERSION}"><link rel="stylesheet" href="assets/css/new-homepage.css?v={VERSION}"><link rel="stylesheet" href="assets/css/ver4-site.css?v={VERSION}"><script src="includes/loader.js"></script><link rel="icon" type="image/svg+xml" href="assets/img/favicon/favicon.svg"><link rel="shortcut icon" href="assets/img/favicon/favicon.ico">{extra_head}
    <!-- JSON-LD -->
    <!-- /JSON-LD -->
</head><body class="dark-theme v4-page"><div id="header-placeholder"></div><main>{body}</main><div id="footer-placeholder"></div></body></html>'''


COMMON_OBJECTS = [("Processes","states, actions, rules and assignments","#2dd4bf","NATIVE"),("Data","lists, relationships and validation","#60a5fa","NATIVE"),("Pages","forms, lists and role-aware views","#fbbf24","NATIVE"),("Access","groups and contextual permissions","#c084fc","NATIVE")]


PAGES = {}

PAGES["platform-2to2.html"] = page(
    "2to2 Platform — Business Software Built from a Living Model | Datapolis",
    "2to2 is an AI-native platform for specification-driven business applications, state-based processes and governed Digital Workers.", "platform-2to2",
    hero("THE 2TO2 PLATFORM", "Business software built from a <span class=\"v4p-accent\">living model.</span>", "In 2to2, the business specification, the no-code application and the running process are not separate artefacts. They are synchronized views of one model that people and AI can understand.", "model", proof=("Specification-driven","Native no-code objects","Governed runtime")) +
    strip("<strong>2to2 is new.</strong> The state-based process technology behind it comes from more than 20 years of Datapolis workflow engineering.", ("SPECIFY","BUILD","RUN","EVOLVE")) +
    cards("ONE PLATFORM", "Four capabilities. One coherent system.", "Each capability works independently. The real advantage comes from keeping them on the same model and runtime.", [
        ("APP AI Creator","Analysts define the business system in structured language. AI completes the definition and builds native 2to2 objects.",( "Explore APP AI Creator","app-ai-creator.html")),
        ("Application platform","Design processes, data, pages and access visually. Every object remains understandable and editable.",( "Explore the platform","process-apps.html")),
        ("State-based process engine","Run real work through explicit states, actions, roles and rules developed from two decades of process experience.",( "Explore the engine","orchestration-engine.html")),
        ("Digital Workers","Give AI governed tasks inside processes, with the same permissions, context and auditability as human work.",( "Explore Digital Workers","digital-workers.html"))], cols=4, soft=True) +
    split("THE LIVING MODEL", "No handoff between documentation, development and operation.", "Traditional projects move information from analyst to developer to administrator. Context is lost at every handoff. 2to2 keeps the definition executable and visible throughout the application lifecycle.", ["Business language remains connected to runtime behaviour.","Visual changes update the application definition.","AI works with explicit objects rather than guessing from screens.","Every published change has an understandable impact."], "What the model contains", "The application is assembled from native, governed building blocks.", COMMON_OBJECTS) +
    compare("A DIFFERENT SOFTWARE LIFECYCLE", "Less translation. Less drift. More control.", "2to2 changes what happens between the business idea and the running application.", "Traditional delivery", "2to2", [
        ("Business requirements","Documents handed to developers","Structured, executable definition","v4p-no","v4p-yes"),
        ("Application output","Generated or hand-written code","Native no-code objects","v4p-no","v4p-yes"),
        ("Documentation after change","Usually updated later","Updated with the model","v4p-no","v4p-yes"),
        ("AI in operation","External assistant","Governed process participant","v4p-no","v4p-yes")]) + final())

PAGES["app-ai-creator.html"] = page(
    "APP AI Creator — The Specification Is the Program | Datapolis",
    "APP AI Creator turns a structured business specification into native 2to2 processes, data, pages and permissions — and keeps both directions synchronized.", "app-ai-creator",
    hero("APP AI CREATOR", "The specification is the program. <span class=\"v4p-accent\">AI is the compiler.</span>", "Business analysts define goals, roles, data, processes, rules, permissions and acceptance scenarios. APP AI Creator clarifies what is missing and compiles the definition into a working 2to2 application.", "compiler", proof=("No generated source code","Impact preview before change","Application ↔ specification")) +
    strip("The output of compilation is not a codebase. It is a set of <strong>native 2to2 objects</strong> that remain visible, editable and governed.", ("ANALYSE","CLARIFY","BUILD","SYNCHRONIZE")) +
    cards("WHAT THE AGENT DOES", "More than prompting. A controlled build process.", "The agent works with a structured definition and a known application model, not an open-ended request to invent software.", [
        ("Find missing decisions","The agent identifies contradictions, undefined outcomes and incomplete permissions before anything is built."),
        ("Create an application plan","Every proposed process, list, page, field and role is visible before the build is applied."),
        ("Compile native objects","The generator creates editable 2to2 objects instead of hiding behaviour in generated source code."),
        ("Keep both views aligned","A no-code change can update the specification; a specification change can update the application.")], cols=4, soft=True) +
    steps("FROM DEFINITION TO APPLICATION", "A repeatable application lifecycle.", "The process is designed for analysts and controlled delivery teams, not one-shot generation.", [
        ("Structure","Describe the business system using a guided application specification."),("Analyse","AI asks for missing decisions and detects contradictions."),("Plan","Review the exact native objects and changes to be created."),("Compile","Build or update the application inside 2to2."),("Evolve","Change either view and synchronize through impact review.")]) +
    split("THE COMPILATION TARGET", "Objects the platform can understand and govern.", "Because the compiler targets the 2to2 object model, the result can be inspected, changed, versioned and run without leaving the platform.", ["No opaque generated repository to maintain.","No gap between a diagram and executable behaviour.","No documentation that becomes obsolete after release.","No AI action outside roles and permissions."], "Application plan", "Before compilation, teams see exactly what will be added or changed.", COMMON_OBJECTS, reverse=True) +
    compare("NOT A PROMPT-TO-CODE TOOL", "The difference is the target of compilation.", "Both approaches use AI, but they produce very different operational outcomes.", "Prompt-to-code", "APP AI Creator", [
        ("Primary input","Natural-language request","Structured business specification","v4p-no","v4p-yes"),("Output","Source code","Native 2to2 objects","v4p-no","v4p-yes"),("Business readability","Falls after generation","Preserved in the model","v4p-no","v4p-yes"),("Reverse synchronization","Rarely available","Built into the lifecycle","v4p-no","v4p-yes"),("Runtime governance","Added separately","Native to the platform","v4p-no","v4p-yes")]) +
    quote("Documentation does not describe the application. <span class=\"v4p-accent\">It participates in building and evolving it.</span>", "The central idea behind APP AI Creator") + final("Bring a specification — even an incomplete one. Let’s turn it into a working application.", "We will use one real business process to show what the agent can clarify, compile and keep synchronized."), alternates=False)

PAGES["process-apps.html"] = page(
    "2to2 Application Platform — Native No-Code Business Applications | Datapolis", "Build and evolve business applications from native processes, data, pages and permissions — with AI assistance and full no-code control.", "process-apps",
    hero("THE APPLICATION PLATFORM", "AI can build it. Your team can <span class=\"v4p-accent\">understand and change it.</span>", "Everything created by APP AI Creator remains available in 2to2’s no-code and low-code designers. Processes, data, pages and permissions are first-class application objects — not generated implementation details.", "apps", proof=("No-code designers","Role-aware interfaces","Versioned publishing")) +
    cards("NATIVE BUILDING BLOCKS", "The whole application stays visible.", "Teams can work at the level that makes sense: structured specification, visual design or a combination of both.", [
        ("Process designer","Define states, actions, transitions, assignments, rules and service-level behaviour."),("Data model","Create lists, fields, relationships, validation and business data structures."),("Page designer","Assemble forms, lists, dashboards and task views for each role."),("Roles & permissions","Control access by identity, role, process state and business context.")], cols=4, soft=True) +
    split("EDITABLE BY DESIGN", "The AI output is the beginning, not a dead end.", "Generated applications often become difficult to change once the initial prompt is over. In 2to2, the output lands directly in the same designers used for manual no-code development.", ["Inspect every process rule and assignment.","Modify data without regenerating the whole application.","Create different pages for different roles.","Preview impact before publishing a model update."], "One coherent application", "Objects share roles, data and lifecycle instead of being connected after the fact.", COMMON_OBJECTS, soft=True) +
    cards("DELIVERY", "Use the application where work happens.", "A process application should fit the operating environment, not force every user into the same screen.", [
        ("2to2 portal","Give teams one place for applications, tasks and governed AI work."),("Embedded experience","Place focused forms and process views inside existing websites or business systems."),("Connected systems","Integrate the application with the data and services the organization already uses.")], cols=3) + final())

PAGES["orchestration-engine.html"] = page(
    "State-Based Process Engine — The Runtime Core of 2to2 | Datapolis", "Model and run business processes through explicit states, actions, roles and rules for humans and Digital Workers.", "orchestration-engine",
    hero("20+ YEARS OF PROCESS ENGINEERING", "Work is not a sequence of screens. It is a <span class=\"v4p-accent\">stateful system.</span>", "The 2to2 process engine models exactly where work is, what may happen next, who may act and which rules apply. The same engine governs people, integrations and Digital Workers.", "process", proof=("State-based","Human and AI execution","Full audit trail")) +
    strip("The process engine is the part of 2to2 with the longest history: <strong>two decades of Datapolis workflow technology</strong> rebuilt for a new platform.", ("STATE","ACTION","ROLE","RULE")) +
    cards("WHY STATES MATTER", "Explicit state makes complex work understandable.", "A state is more than a status label. It is the operating context for the application.", [
        ("What can happen next","Actions and transitions are available only when the process state allows them."),("Who may act","Assignments and permissions change with role, ownership, data and state."),("What must be true","Business rules validate decisions before the process moves forward."),("What happens automatically","Timers, integrations and Digital Workers run as controlled process activities.")], cols=4, soft=True) +
    split("PROCESS-NATIVE APPLICATIONS", "The interface follows the process — not the other way around.", "Forms and pages should reflect the current business situation. State gives 2to2 the context to show the right data, actions and guidance to each participant.", ["Different roles can see different actions in the same state.","A transition can require validation, approval or AI work.","Escalation and service levels belong to the process definition.","Every state change becomes part of the audit trail."], "A state carries context", "The engine resolves the next valid behaviour from the model.", [("Available actions","what may happen now","#2dd4bf","NOW"),("Assignments","who owns the work","#60a5fa","ROLE"),("Business rules","what must be true","#fbbf24","RULE"),("Automation","what runs without a click","#c084fc","AUTO")]) +
    cards("BUILT FOR REAL PROCESSES", "Complexity belongs in a model people can inspect.", "The engine supports the patterns that appear when a process leaves the whiteboard and enters an enterprise.", [
        ("Parallel work","Coordinate multiple participants without losing one case history."),("Return and rework","Model rejection, correction and repeated review explicitly."),("Time and escalation","React to deadlines, delays and service-level commitments."),("Subprocesses","Reuse controlled process fragments without copying logic.")], cols=4, soft=True) + final())

PAGES["digital-workers.html"] = page(
    "Digital Workers — Governed AI Inside Business Processes | Datapolis", "Digital Workers execute assigned AI work inside 2to2 processes with explicit context, permissions, oversight and audit.", "digital-workers",
    hero("AI AT RUN TIME", "AI that works inside the process — <span class=\"v4p-accent\">not beside it.</span>", "A Digital Worker receives a defined task, the required business context and explicit permissions. It acts inside the same process as people and returns an outcome the process can validate, route and audit.", "workers", proof=("Assigned work","Explicit permissions","Human oversight")) +
    cards("A PROCESS PARTICIPANT", "What makes an AI agent a Digital Worker.", "The difference is not intelligence. It is the operating contract around the intelligence.", [
        ("A defined task","The process assigns a specific activity with a clear expected outcome."),("Bounded context","The worker receives only the case data, documents and tools required for the task."),("Explicit authority","Permissions define what the worker may read, create, change or recommend."),("Recorded result","Inputs, actions and outcomes remain attached to the process history.")], cols=4, soft=True) +
    split("BUILD TIME AND RUN TIME", "APP AI Creator builds. Digital Workers operate.", "2to2 uses AI in two distinct moments. The creator helps analysts define and build the application. Digital Workers execute governed work after the application is running.", ["Different agents, responsibilities and permissions.","The same application model connects both moments.","Run-time AI cannot silently change the process definition.","Human approval can be required before consequential actions."], "Two AI roles", "Keeping the roles separate makes the system easier to control and explain.", [("APP AI Creator","analyses and builds the application model","#2dd4bf","BUILD"),("Digital Worker","executes assigned process activities","#60a5fa","RUN"),("Human owner","reviews, decides and remains accountable","#fbbf24","OWN")], reverse=True) +
    compare("PEOPLE AND DIGITAL WORKERS", "Different strengths. The same operating system.", "2to2 does not pretend humans and AI are identical. It gives both a shared process context.", "Human participant", "Digital Worker", [
        ("Best at","Judgement, accountability, exceptions","Scale, analysis, repetitive knowledge work","v4p-yes","v4p-yes"),("Receives work from","Process assignment","Process assignment","v4p-yes","v4p-yes"),("Acts under permissions","Yes","Yes","v4p-yes","v4p-yes"),("Escalates uncertainty","By decision","By configured handoff","v4p-yes","v4p-yes"),("Actions recorded","Yes","Yes","v4p-yes","v4p-yes")]) + final())

PAGES["how-it-works.html"] = page(
    "How 2to2 Works — From Business Idea to Governed Operation | Datapolis", "See the complete 2to2 lifecycle: structure the business specification, compile native application objects, run the process and keep documentation synchronized.", "how-it-works",
    hero("FROM IDEA TO OPERATION", "Define the business system once. <span class=\"v4p-accent\">Run and evolve it continuously.</span>", "2to2 connects analysis, application development and process operation through one living model. Teams can begin with structured documentation, visual no-code design or both.", "compiler", proof=("Analyst-led definition","AI-assisted build","Controlled evolution")) +
    steps("THE COMPLETE LOOP", "Five stages. One model.", "The lifecycle is iterative, but the information does not have to be recreated at every stage.", [
        ("Define","Structure goals, roles, data, processes, permissions and acceptance scenarios."),("Clarify","Use AI to find missing decisions, contradictions and undefined outcomes."),("Compile","Create native processes, data, pages, roles and Digital Worker tasks."),("Run","Publish the application and execute governed work with people and AI."),("Evolve","Change the specification or no-code application and synchronize through impact review.")]) +
    split("THE CHANGE LOOP", "Application and specification evolve together.", "A running business application will change. 2to2 makes the change visible in both the business definition and the operational model.", ["A visual no-code change can propose a documentation update.","A specification change can propose changes to native objects.","Teams review impact before publishing.","Version history preserves the evolution of the business system."], "Example update", "A new approval state changes several connected objects, all shown before publishing.", [("Process","add Approval state and transitions","#2dd4bf","+3"),("Permissions","allow Compliance Manager action","#c084fc","+2"),("Page","show approval decision panel","#fbbf24","+1"),("Specification","record the new business rule","#60a5fa","SYNC")], soft=True) +
    cards("WHO WORKS WITH 2TO2", "One model, different perspectives.", "Each participant sees the level of detail needed for their responsibility.", [
        ("Business analyst","Defines the application in structured business language and resolves decisions."),("Application designer","Refines processes, data, pages and access in visual tools."),("Business user","Works through role-aware pages, tasks and process actions."),("Digital Worker","Executes assigned AI tasks inside process rules and permissions.")], cols=4) + final())

PAGES["how-it-works-overview.html"] = page(
    "The Living Application Model — Specification and Application Aligned | Datapolis", "Understand the central 2to2 idea: the business specification and the working no-code application are synchronized views of one living model.", "how-it-works-overview",
    hero("THE LIVING APPLICATION MODEL", "One business system. <span class=\"v4p-accent\">Two synchronized views.</span>", "The structured specification expresses intent in language people and AI can understand. The no-code application expresses the same system as executable processes, data, pages and permissions.", "model", proof=("Human-readable","Machine-actionable","Always-current")) +
    split("THE SPECIFICATION VIEW", "Define what the business system means.", "A useful application specification goes beyond a feature list. It describes the decisions the running system must make and control.", ["Goals and success conditions.","Roles, responsibilities and ownership.","Business data and relationships.","Process states, actions and exceptions.","Permissions and acceptance scenarios."], "Structured, not frozen", "The specification remains connected to native application objects.", [("Business intent","why the application exists","#2dd4bf","WHY"),("Operating rules","how decisions are made","#fbbf24","RULE"),("Acceptance scenarios","what correct behaviour means","#60a5fa","TEST")]) +
    split("THE APPLICATION VIEW", "Design and run the working system.", "The same model becomes a no-code application that teams can inspect, change and publish without translating it into a separate implementation language.", ["State-based processes coordinate work.","Data structures hold business context.","Pages adapt to role and state.","Permissions govern every participant.","Digital Workers execute explicit tasks."], "Native application objects", "Every object has a business meaning and an operational effect.", COMMON_OBJECTS, reverse=True, soft=True) +
    cards("SYNCHRONIZATION", "A change is a controlled model operation.", "2to2 shows the consequences of a change before it updates the working application or its specification.", [
        ("Detect","Identify which model objects and business statements are affected."),("Explain","Present the impact in language analysts and designers can review."),("Apply","Update native objects through a controlled build and publishing step.")], cols=3) +
    quote("The goal is not better documentation. The goal is software that <span class=\"v4p-accent\">cannot silently drift away from what the business defined.</span>", "The living application model") + final())

PAGES["humans-agents.html"] = page(
    "People + Digital Workers — One Governed Process | Datapolis", "People and Digital Workers work inside the same 2to2 process, with explicit assignments, permissions, handoffs and one audit trail.", "humans-agents",
    hero("PEOPLE + DIGITAL WORKERS", "Different executors. <span class=\"v4p-accent\">One governed process.</span>", "2to2 assigns each activity to the participant best suited to it. Humans keep judgement and accountability. Digital Workers add speed and scale. The process coordinates both.", "workers", proof=("Shared context","Explicit handoffs","One audit trail")) +
    cards("THE SHARED OPERATING LAYER", "Collaboration without invisible handoffs.", "The process is the contract between every participant — human, AI or system.", [
        ("Same case context","Everyone works with the current business data and process state."),("Same rules","Transitions, validation and approvals apply regardless of who performs the activity."),("Explicit ownership","Every task has an owner, expected outcome and escalation path."),("One history","Human and AI work forms one chronological, auditable process record.")], cols=4, soft=True) +
    split("DESIGN THE HANDOFF", "AI should know when to stop.", "A useful Digital Worker does not hide uncertainty. The process defines confidence thresholds, review points and escalation to a responsible person.", ["Routine analysis can run automatically.","Exceptions return to a named role.","Consequential actions can require human approval.","A person can see the inputs and reasoning context used for the outcome."], "Example division of work", "Vendor onboarding combines speed with accountable decisions.", [("Digital Worker","extracts company data and screens documents","#60a5fa","AI"),("Compliance Manager","reviews high-risk cases","#fbbf24","HUMAN"),("Process","routes, validates and records the outcome","#2dd4bf","2to2")], reverse=True) +
    compare("ONE PROCESS, DIFFERENT STRENGTHS", "Do not automate the person out of the system.", "Use AI where it improves flow and keep people where judgement and accountability matter.", "People", "Digital Workers", [
        ("Ambiguous judgement","Strong","Escalate when uncertain","v4p-yes","v4p-no"),("High-volume analysis","Limited by capacity","Strong","v4p-no","v4p-yes"),("Legal accountability","Own decisions","Support decisions","v4p-yes","v4p-no"),("Process compliance","Guided by process","Enforced by process","v4p-yes","v4p-yes")]) + final())

PAGES["governance-control.html"] = page(
    "Governance & Control — Govern Human and AI Work at Runtime | Datapolis", "2to2 applies roles, permissions, approvals, state rules and audit while humans and Digital Workers execute business processes.", "governance-control",
    hero("GOVERNANCE & CONTROL", "AI without an operating framework is a liability. <span class=\"v4p-accent\">The process provides one.</span>", "2to2 governs work at the moment it happens. Every participant acts through a process state, an assigned role, explicit permissions and a traceable decision path.", "governance", proof=("Contextual access","Approval control","Auditable execution")) +
    cards("CONTROL IN PRACTICE", "Governance is part of execution.", "Policies matter only when the running system can apply them consistently.", [
        ("Identity and role","Know whether the participant is a person, Digital Worker, service or integration."),("State-aware permission","Allow an action only for the right role in the right process context."),("Approval and separation","Require accountable review and separate conflicting responsibilities."),("Complete history","Record inputs, actions, transitions, outcomes and responsible participants.")], cols=4, soft=True) +
    split("PROCESS AS POLICY ENGINE", "The process turns policy into executable boundaries.", "Documents can say what should happen. A governed process determines what can happen and blocks behaviour outside the model.", ["Permissions can depend on state and case data.","AI tools are exposed only for an assigned task.","Sensitive transitions can require named approval.","Exceptions follow a visible escalation path."], "Runtime control", "The current state resolves the applicable control set for every action.", [("Identity","who is acting","#60a5fa","WHO"),("Context","which case and state","#2dd4bf","WHERE"),("Authority","what is permitted","#c084fc","MAY"),("Evidence","what was recorded","#fbbf24","AUDIT")]) +
    cards("REGULATED ENVIRONMENTS", "Designed for work that must be explainable.", "Datapolis process technology has been used in banking, energy, industry and government — environments where control cannot be an afterthought.", [
        ("Traceable decisions","Reconstruct who did what, when, under which process state and rule."),("Controlled change","Review and publish model changes through explicit versions."),("Human oversight","Keep responsible roles in the loop for defined decisions and exceptions.")], cols=3, soft=True) + final())

PAGES["pilot-scale.html"] = page(
    "Pilot to Production — Prove 2to2 on One Real Process | Datapolis", "Start with one real business process, build a production-shaped 2to2 application and scale the same model across teams and applications.", "pilot-scale",
    hero("PILOT TO PRODUCTION", "Start with one process. <span class=\"v4p-accent\">Do not build a disposable demo.</span>", "A good 2to2 pilot uses real roles, rules and exceptions. It proves the living specification, the native application model and governed execution on work your organization actually understands.", "pilot", proof=("Focused scope","Production-shaped model","Clear success criteria")) +
    steps("A CONTROLLED START", "Five steps from process to evidence.", "The pilot is designed to answer whether 2to2 improves delivery and operation — not merely whether a screen can be generated.", [
        ("Choose","Select one valuable process with a clear owner and manageable integration scope."),("Specify","Structure goals, roles, data, states, permissions and acceptance scenarios."),("Build","Use APP AI Creator and no-code designers to create the native application."),("Run","Test with real participants, representative cases and governed AI work."),("Decide","Measure the result and define the next application or production step.")]) +
    cards("WHAT THE PILOT SHOULD PROVE", "Evidence, not theatre.", "A focused pilot can validate the central claims of the platform without requiring an enterprise-wide programme.", [
        ("Analyst productivity","Can the specification become a working application with less translation and rework?"),("Application clarity","Can business and technical teams inspect the same model and understand its behaviour?"),("Operational control","Can people and Digital Workers execute under explicit roles, rules and audit?"),("Change discipline","Can a real change update the application and documentation without drift?")], cols=4) +
    split("SCALE WITHOUT REBUILDING", "The production model begins in the pilot.", "The same native objects, process engine and publishing model continue after validation. Scaling means adding users, cases, integrations and applications — not translating the prototype into another technology.", ["Promote the validated application model.","Add integrations when the process value is proven.","Reuse roles, data patterns and process fragments.","Build the next application with the same delivery method."], "Pilot output", "A successful pilot leaves reusable assets and explicit evidence.", [("Application model","native 2to2 objects","#2dd4bf","KEEP"),("Specification","current and versioned","#60a5fa","KEEP"),("Success evidence","agreed operational measures","#fbbf24","MEASURE"),("Scale plan","next applications and integrations","#c084fc","NEXT")], soft=True) + final("Bring the process your team knows best.", "We will define the pilot around one concrete workflow, its real participants and a decision you can measure."))

PAGES["ai-inside-workflows.html"] = page(
    "AI Inside Workflows — Governed AI in Business Processes | Datapolis", "Put AI inside explicit business process tasks with context, permissions, handoffs and audit instead of leaving work in disconnected chat sessions.", "ai-inside-workflows",
    hero("AI INSIDE WORKFLOWS", "AI should receive work from the process — <span class=\"v4p-accent\">not from an improvised prompt.</span>", "Inside 2to2, AI works as a Digital Worker. It receives an assigned activity, the correct case context and bounded authority, then returns an outcome the process can validate and route.", "workers", proof=("Process-assigned tasks","Bounded tools and data","Visible outcomes")) +
    cards("THE OPERATING CONTRACT", "Four things every AI task needs.", "A model can be powerful and still operate safely when the surrounding work is explicit.", [
        ("Task","A defined activity and expected output."),("Context","The current case, documents, data and process state."),("Authority","The exact tools and changes allowed for this activity."),("Handoff","The next state, reviewer or escalation path after the result.")], cols=4, soft=True) +
    split("FROM CHAT TO PROCESS", "Keep AI work attached to the business case.", "A chat can help an individual. It does not automatically create ownership, process state, permissions or an enterprise record. 2to2 supplies that missing operating layer.", ["No need to copy results from chat into the system of record.","The worker receives current case data instead of a manual prompt summary.","The process knows whether the task succeeded, failed or needs review.","The outcome becomes part of the same audit trail as human work."], "Example AI activities", "Digital Workers can perform different bounded tasks within one process.", [("Document review","extract, classify and compare","#60a5fa","AI"),("Case analysis","evaluate rules and evidence","#2dd4bf","AI"),("Drafting","prepare a response for approval","#fbbf24","AI"),("System update","act only when explicitly permitted","#c084fc","TOOL")]) +
    cards("EXAMPLE USE CASES", "AI where work already has structure.", "The strongest candidates combine knowledge work with a clear process outcome.", [
        ("Vendor onboarding","Review documents, screen risk and route exceptions."),("Contract lifecycle","Extract terms, compare clauses and prepare review."),("Service operations","Classify requests, propose resolution and escalate uncertainty."),("Regulated review","Assemble evidence while preserving accountable approval.")], cols=4, soft=True) + final())

PAGES["security-governance.html"] = page(
    "Security & Governance — Process-Native Control for 2to2 | Datapolis", "Control access and execution in 2to2 through identity, contextual permissions, process state, approvals, audit and versioned application models.", "security-governance",
    hero("SECURITY & GOVERNANCE", "Security controls access. The process must also <span class=\"v4p-accent\">control execution.</span>", "2to2 combines application access with process-native governance. A participant may see a case yet still be unable to perform an action unless role, state, ownership and business rules allow it.", "governance", proof=("Role and state context","Controlled publishing","Explainable history")) +
    cards("MULTIPLE CONTROL LAYERS", "Defence through explicit structure.", "The platform applies controls to the application model and to every running process case.", [
        ("Identity","Authenticate people, services and Digital Workers as distinct participants."),("Application access","Control who can enter an application and use its data."),("Process authority","Resolve available actions from role, state, ownership and rules."),("Change governance","Version, review and publish application model changes deliberately.")], cols=4, soft=True) +
    split("CONTEXTUAL PERMISSIONS", "Access changes with the business situation.", "Static roles alone cannot express many real controls. 2to2 combines role with the current process state and case context.", ["A requester can edit while a case is in Draft.","A reviewer can decide only when Review is active.","A Digital Worker can use a tool only during its assigned activity.","A sensitive transition can require separation of duties."], "Permission decision", "The runtime resolves several dimensions before allowing an action.", [("Identity","authenticated participant","#60a5fa","WHO"),("Role","business responsibility","#c084fc","ROLE"),("State","current process context","#2dd4bf","WHEN"),("Rule","case-specific condition","#fbbf24","IF")]) +
    compare("ACCESS AND EXECUTION", "Both matter. They solve different problems.", "2to2 treats process governance as a separate control layer rather than assuming login is enough.", "Access control", "Execution control", [
        ("Primary question","May this participant enter?","May this action happen now?","v4p-yes","v4p-yes"),("Typical context","Application and data","Role, state, ownership and rule","v4p-yes","v4p-yes"),("AI relevance","Can the agent connect?","What may the agent do in this task?","v4p-no","v4p-yes"),("Evidence","Authentication and access logs","Complete business process history","v4p-no","v4p-yes")]) + final())

PAGES["why-not-copilots.html"] = page(
    "Why Not Copilots? AI Assistance vs Governed Digital Work | Datapolis", "Copilots help individuals. Digital Workers execute assigned work inside governed processes with context, permissions, handoffs and audit.", "why-not-copilots",
    hero("COPILOTS AND DIGITAL WORKERS", "Copilots are useful. They are not <span class=\"v4p-accent\">an operating model for work.</span>", "A copilot assists a person in a conversation. A Digital Worker participates in a business process. The distinction matters when work crosses roles, systems, approvals and accountability boundaries.", "workers", proof=("Assist vs execute","Conversation vs process","Personal context vs case context")) +
    compare("TWO DIFFERENT AI ROLES", "Choose the model that matches the work.", "The point is not to replace copilots. It is to avoid using a personal assistant where the organization needs a governed process participant.", "Copilot", "Digital Worker", [
        ("Starts from","A user prompt","A process assignment","v4p-no","v4p-yes"),("Primary context","Conversation and user","Case data and process state","v4p-no","v4p-yes"),("Authority","Often broad or user-mediated","Explicit for the assigned task","v4p-no","v4p-yes"),("Handoff","User decides what happens next","Process routes the outcome","v4p-no","v4p-yes"),("Audit","Conversation history","Business process history","v4p-no","v4p-yes")]) +
    cards("WHERE COPILOTS FIT", "Use assistance for individual productivity.", "Copilots are strong when a person remains in direct control of a short-lived interaction.", [("Explore","Ask questions and investigate information."),("Draft","Create text, summaries and ideas for personal review."),("Navigate","Help a user find information or operate a tool.")], cols=3, soft=True) +
    cards("WHERE DIGITAL WORKERS FIT", "Use process participation for operational work.", "Digital Workers are designed for repeatable activities that need ownership, context and control.", [("Execute","Complete an assigned business activity."),("Route","Return a structured outcome the process can act on."),("Escalate","Hand uncertainty to the right accountable role.")], cols=3) +
    quote("The question is not whether AI can do the task. It is whether the organization can <span class=\"v4p-accent\">control, explain and own the result.</span>", "Why 2to2 puts AI inside processes") + final())

PAGES["about.html"] = page(
    "About Datapolis — 20+ Years of Process Software | Datapolis", "Datapolis has built state-based workflow and business process software for more than 20 years. 2to2 is the next generation of that experience.", "about",
    hero("ABOUT DATAPOLIS", "2to2 is new. Our process experience <span class=\"v4p-accent\">is not.</span>", "For more than 20 years, Datapolis has built software that turns business processes into working systems. 2to2 carries that state-based process knowledge into an AI-native application platform.", "process", secondary=("See our customers","customers.html"), proof=("20+ years","Enterprise workflow","Polish product company")) +
    stats((("20+","years building workflow and process platforms"),("1000s","of business processes delivered with Datapolis products"),("Enterprise","experience across regulated and complex environments"))) +
    cards("OUR EVOLUTION", "The technology changed. The process problem remained.", "Each product generation addressed the same underlying need: make business rules executable, visible and easier to change.", [
        ("State-based workflow","Datapolis began by building visual process technology around explicit states and actions."),("Microsoft platforms","Workbox and DPS brought that process model to SharePoint Server and Microsoft 365."),("2to2","The new platform connects structured application specifications, native no-code objects and governed AI work.")], cols=3) +
    split("HOW WE THINK", "Business software should remain understandable after it starts running.", "We believe the people who own a business process should be able to see how their system works — its states, rules, data, permissions and participants.", ["The process is a business asset, not implementation detail.","AI should reduce translation without creating opacity.","Governance belongs inside execution.","A new platform should respect the systems customers already run."], "Two product generations", "Datapolis supports established Microsoft workflow customers while building the next generation.", [("Workbox & DPS","workflow products for Microsoft environments","#60a5fa","ESTABLISHED"),("2to2","AI-native business application platform","#2dd4bf","NEW")], soft=True) +
    quote("We are not starting with AI and looking for a problem. We are applying AI to a problem we have worked on for more than two decades.", "Datapolis") + final())

PAGES["customers.html"] = page(
    "Customers — Organizations Using Datapolis Workflow Products | Datapolis", "Organizations across industry, energy, finance and government use Datapolis workflow products. 2to2 is new; the process experience behind it is proven.", "customers",
    hero("DATAPOLIS CUSTOMERS", "Process technology trusted in <span class=\"v4p-accent\">real operating environments.</span>", "Datapolis workflow products have supported business processes in global enterprises and public organizations. 2to2 is a new platform and is not presented here as a product already used by these customers.", "process", primary=("Talk to Datapolis","contact.html"), secondary=("About our experience","about.html"), proof=("Enterprise deployments","Regulated industries","Long-term customer environments")) +
    strip("The organizations below use or have used <strong>Datapolis workflow products</strong>. Their presence does not imply deployment of 2to2.", ("WORKBOX","DPS","PROCESS PROJECTS")) +
    f'''<section class="v4p-section v4p-section-soft"><div class="v4p-shell">{head("SELECTED ORGANIZATIONS","Organizations using Datapolis workflow products.","A selection from the broader Datapolis customer history.",True)}{logos()}</div></section>''' +
    cards("ENVIRONMENTS", "Process software for work that cannot live in a spreadsheet.", "Datapolis products have been used where processes cross teams, responsibilities and systems.", [
        ("Industry & manufacturing","Operational approvals, documents, quality and cross-department workflow."),("Energy & infrastructure","Controlled processes in large, distributed organizations."),("Finance & regulated business","Traceable decisions, permissions and accountable review."),("Government & public sector","Formal procedures, documents and long-lived on-premise environments.")], cols=4) +
    split("PROVEN EXPERIENCE, HONEST POSITIONING", "The customer history belongs to Datapolis. 2to2 must earn its own.", "We use the experience from established products to design 2to2, but we do not claim that legacy customers already run the new platform.", ["2to2 is a new product generation.","The process engine draws on long Datapolis experience.","Established Microsoft products remain supported.","New 2to2 pilots begin with focused, measurable processes."], "What carries forward", "Experience becomes product design — not an invented reference list.", [("Process patterns","two decades of state-based modelling","#2dd4bf","PROVEN"),("Enterprise lessons","permissions, exceptions and change","#60a5fa","PROVEN"),("2to2 adoption","new pilots and new evidence","#fbbf24","NEXT")], soft=True) + final())

contact_body = hero("TALK TO DATAPOLIS", "Bring one real process. <span class=\"v4p-accent\">We’ll talk concretely.</span>", "Tell us what the process does, who participates and where it gets stuck. We can discuss a focused 2to2 pilot, an existing Datapolis deployment or Microsoft workflow migration.", "model", primary=("Go to the form","#contact-form"), secondary=("Email us","mailto:office@datapolis.com"), proof=("2to2 pilots","Workbox & DPS","SharePoint workflow migration"))
contact_body += '''<section class="v4p-section v4p-section-soft" id="contact-form"><div class="v4p-shell"><div class="v4p-contact-grid"><div><p class="v4p-kicker">CONTACT</p><h2 style="font-size:clamp(32px,4vw,50px);margin-bottom:28px">Start with the situation, not a product name.</h2><div class="v4p-contact-card"><h3>Email</h3><p><a href="mailto:office@datapolis.com">office@datapolis.com</a></p></div><div class="v4p-contact-card" style="margin-top:14px"><h3>What helps us prepare</h3><p>Process name, current system, approximate number of users, the main bottleneck and whether AI participation is part of the goal.</p></div><div class="v4p-contact-card" style="margin-top:14px"><h3>Response time</h3><p>We normally reply within one or two business days.</p></div></div><div class="v4p-form-frame"><div id="workflow-form-www-contacts"></div><script src="https://2to2.ai/embed-workflow.js" data-workflow="www-contacts" data-container="workflow-form-www-contacts" data-base-url="https://2to2.ai"></script></div></div></div></section>'''
contact_body += cards("A GOOD FIRST 2TO2 PILOT", "Focused enough to finish. Real enough to teach us something.", "The best starting process has a clear owner, visible business value and enough structure to test the living application model.", [("One process owner","A person who can resolve rules and make scope decisions."),("Real participants","The roles that actually perform, review and approve the work."),("Representative exceptions","At least one non-happy path so the process model is genuinely tested."),("A measurable outcome","Time, effort, quality, control or another result the pilot can demonstrate.")], cols=4) + final()
PAGES["contact.html"] = page("Contact Datapolis — 2to2 Pilots and Workflow Products", "Contact Datapolis about a focused 2to2 pilot, Digital Workers, Workbox, DPS or SharePoint workflow migration.", "contact", contact_body)

sharepoint_body = hero("MICROSOFT PRODUCTS", "Keep critical Microsoft workflows running — <span class=\"v4p-accent\">and plan what comes next.</span>", "Workbox and Datapolis Process System support organizations that run business processes in Microsoft 365 and SharePoint Server. We also help teams address the end of WWF3-based workflow support.", "process", primary=("Book a migration call","#booking"), secondary=("Contact us","contact.html"), proof=("Microsoft 365","SharePoint Server SE","On-premise experience"))
sharepoint_body += strip("These are <strong>established Datapolis products</strong>, separate from the new 2to2 platform and supported for existing Microsoft environments.", ("WORKBOX","DPS","WWF3 MIGRATION"))
sharepoint_body += cards("MICROSOFT WORKFLOW PRODUCTS", "Choose the path that matches your environment.", "Datapolis has spent years building process technology around Microsoft collaboration platforms.", [
    ("Workbox for Microsoft 365","Create and run business workflows connected to the Microsoft 365 environment."),("Datapolis Process System","State-based workflow technology for SharePoint Server deployments."),("WWF3 migration","Assess SharePoint Designer, Nintex and other WWF3-based workflows before support ends.")], cols=3, soft=True, section_id="wwf3")
sharepoint_body += split("WWF3 END OF SUPPORT", "Do not wait for a critical workflow to become an unsupported dependency.", "Microsoft’s retirement of SharePoint 2010 workflow support in SharePoint Server Subscription Edition requires organizations to identify what still runs on WWF3 and choose a controlled migration path.", ["Inventory active and business-critical workflows.","Identify platform, integration and compliance constraints.","Separate workflows worth migrating from those worth retiring.","Choose a target that respects cloud or on-premise requirements."], "Migration assessment", "A short assessment should produce decisions, not another inventory spreadsheet.", [("Workflow portfolio","active, critical and redundant flows","#60a5fa","MAP"),("Constraints","on-premise, data and integration needs","#fbbf24","CHECK"),("Target path","Workbox, DPS, 2to2 or retirement","#2dd4bf","DECIDE")])
sharepoint_body += '''<section class="v4p-section v4p-section-soft" id="booking"><div class="v4p-shell"><div class="v4p-contact-grid"><div><p class="v4p-kicker">20-MINUTE WORKFLOW CALL</p><h2 style="font-size:clamp(32px,4vw,50px)">Tell us what still runs. We’ll tell you what we would do.</h2><p style="color:#94a3b8;font-size:16px;line-height:1.7">A direct conversation about your SharePoint version, workflow portfolio, constraints and realistic migration options.</p><div class="v4p-note"><strong>Straight answer</strong><p>The right conclusion may be Workbox, DPS, 2to2, another Microsoft path or retirement of the workflow.</p></div></div><div class="v4p-form-frame"><iframe src="https://2to2.ai/workflow/kampanialn/form?embed=true" title="Book a 20-minute call with Datapolis" loading="lazy"></iframe></div></div></div></section>'''
sharepoint_body += final("Need a path for Microsoft workflows — not another platform pitch?", "Show us the environment and constraints. We will discuss the practical options, including when a Datapolis product is not the right answer.")
PAGES["sharepoint.html"] = page("Microsoft Workflow Products — Workbox, DPS and WWF3 Migration | Datapolis", "Datapolis Workbox and DPS support Microsoft 365 and SharePoint Server workflows, including practical assessment and migration from WWF3-based solutions.", "sharepoint", sharepoint_body, alternates=False)

legal_body = '''<section class="v4p-hero" style="min-height:auto;padding-bottom:75px"><div class="v4p-shell"><p class="v4p-eyebrow">LEGAL</p><h1>Legal information.</h1><p class="v4p-hero-lead">Privacy, terms of website use and company information for Datapolis Sp. z o.o.</p></div></section><section class="v4p-section"><div class="v4p-shell"><div class="v4p-split" style="align-items:start"><div class="v4p-split-copy"><p class="v4p-kicker">PRIVACY POLICY</p><h2>How we handle information.</h2><p>Datapolis Sp. z o.o. collects information provided directly through contact forms, demo requests and email. We use it to respond to inquiries, provide services and improve our offering.</p><ul><li>We apply appropriate technical and organizational safeguards.</li><li>We use submitted data for the purpose connected to the inquiry.</li><li>For privacy questions, contact office@datapolis.com.</li></ul><p style="font-size:12px;color:#64748b">Last updated: January 2026</p></div><div class="v4p-side-panel"><h3>Terms of website use</h3><p>datapolis.com is provided for informational purposes. Its content, graphics, logos and software are the property of Datapolis Sp. z o.o. and protected by applicable intellectual property laws.</p><p>Users may not use the website for unlawful purposes. Datapolis is not liable for indirect, incidental or consequential damages arising from use of this informational website.</p><p style="font-size:12px;color:#64748b">Last updated: January 2026</p></div></div></div></section><section class="v4p-section v4p-section-soft" id="imprint"><div class="v4p-shell">''' + head("IMPRINT","Company information.","") + '''<div class="v4p-grid v4p-grid-3"><article class="v4p-card"><h3>Datapolis Sp. z o.o.</h3><p>ul. Dzielna 21/121a<br>01-029 Warsaw, Poland</p></article><article class="v4p-card"><h3>Registration</h3><p>KRS: 0000003324<br>NIP: 5272336739</p></article><article class="v4p-card"><h3>Contact</h3><p><a href="mailto:office@datapolis.com">office@datapolis.com</a></p></article></div></div></section>'''
PAGES["legal.html"] = page("Legal — Datapolis", "Datapolis legal information, privacy policy, terms of website use and company imprint.", "legal", legal_body)


def main():
    for name, content in PAGES.items():
        (ROOT / name).write_text(content, encoding="utf-8")
    print(f"generated {len(PAGES)} English ver4 subpages")


if __name__ == "__main__":
    main()
